version: "3"

vars:
  JAVA_CLASS: org.advancedcloud.examples.FairQueuingTaskScheduling
  BATCH_JAVA_CLASS: org.advancedcloud.examples.FairQueuingBatchScheduling
  TASK_FILE: tasks.csv
  HEADERS:
    - task_id
    - length
    - vm_id
    - thread
    - start_time
    - finish_time

tasks:
  default:
    cmds:
      - task: run-batches

  compile:
    desc: Compile the Maven project
    cmds:
      - mvn clean compile

  run:
    desc: Run the simulation
    deps: [compile]
    cmds:
      - mvn exec:java -Dexec.mainClass={{.JAVA_CLASS}}

  run-batches-*-*:
    desc: Run the simulation in batches
    deps: [compile]
    ignore_error: true
    vars:
      LIMIT: "{{index .MATCH 0}}"
      BATCH_SIZE: "{{index .MATCH 1}}"
    cmds:
      - rm results.csv virtual_times.csv
      - |
        for ((OFFSET = 0; OFFSET < {{.LIMIT}}; OFFSET += {{.BATCH_SIZE}})); do
          echo "Running batch starting at task #$OFFSET"
          mvn exec:java -Dexec.mainClass={{.BATCH_JAVA_CLASS}} -Dexec.args="$OFFSET {{.LIMIT}} {{.BATCH_SIZE}}"
        done
        sed -i '1i {{ join "," .HEADERS }}' results.csv
    silent: false

  setup:
    cmds:
      - mvn clean install
      - virtualenv .venv
      - source .venv/bin/active
      - pip install -r requirements.txt

  visualize:
    cmds:
      - python visualize.py
